import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/context/themeContext";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "next news portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={inter.className}
      >
     <ThemeProvider>
     <Navbar></Navbar>
       <main className=" min-h-screen max-w-7xl mx-auto px-4 sm:px-6 lg:px-8
">
       {children}
       </main>
        <Footer></Footer>
     </ThemeProvider>
      </body>
    </html>
  );
}
